<x-app-layout>
    @component('components.offer-image')
    @endcomponent
    @component('components.cons-bages')
    @endcomponent
    @component('components.categories')
    @endcomponent
    @component('components.slider')
    @endcomponent
    @component('components.special-offer-card')
    @endcomponent
    @component('components.recomendation')
    @endcomponent
</x-app-layout>
